id: IA6E6FF51
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T04:46:52+00:00'
last_modified: '2022-06-16T04:33:35.241767+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1PD95812
  title: གསུང་ཐོར་བུ། བློ་གྲོས་དཔལ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    76C7:
      image_group_id: I1KG15395
      title: Volume 1 of byang chub lam gyi rim pa'i khrid chen brgyad phyogs gcig
        tu bsgrigs pa/
      total_pages: 852
      order: 1
      base_file: 76C7.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
